export const books = [
  {
    id: 1,
    image: 'https://placehold.co/300x400?text=Libro+1',
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    genre: 'Novela',
  },
  {
    id: 2,
    image: 'https://placehold.co/300x400?text=Libro+2',
    title: 'El amor en los tiempos del cólera',
    author: 'Gabriel García Márquez',
    genre: 'Novela',
  },
  {
    id: 3,
    image: 'https://placehold.co/300x400?text=Libro+3',
    title: 'Rayuela',
    author: 'Julio Cortázar',
    genre: 'Novela',
  },
  {
    id: 4,
    image: 'https://placehold.co/300x400?text=Libro+4',
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    genre: 'Novela',
  },
  {
    id: 5,
    image: 'https://placehold.co/300x400?text=Libro+5',
    title: 'El principito',
    author: 'Antoine de Saint-Exupéry',
    genre: 'Infantil',
  },
  {
    id: 6,
    image: 'https://placehold.co/300x400?text=Libro+6',
    title: 'Alicia en el país de las maravillas',
    author: 'Lewis Carroll',
    genre: 'Infantil',
  },
  {
    id: 7,
    image: 'https://placehold.co/300x400?text=Libro+7',
    title: 'El Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasía',
  },
  {
    id: 8,
    image: 'https://placehold.co/300x400?text=Libro+8',
    title: 'El señor de los anillos',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasía',
  },
  {
    id: 9,
    image: 'https://placehold.co/300x400?text=Libro+9',
    title: 'Harry Potter y la piedra filosofal',
    author: 'J.K. Rowling',
    genre: 'Fantasía',
  },
  {
    id: 10,
    image: 'https://placehold.co/300x400?text=Libro+10',
    title: '1984',
    author: 'George Orwell',
    genre: 'Ciencia ficción',
  },
  {
    id: 11,
    image: 'https://placehold.co/300x400?text=Libro+11',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    genre: 'Ciencia ficción',
  },
  {
    id: 12,
    image: 'https://placehold.co/300x400?text=Libro+12',
    title: 'Un mundo feliz',
    author: 'Aldous Huxley',
    genre: 'Ciencia ficción',
  },
  {
    id: 13,
    image: 'https://placehold.co/300x400?text=Libro+13',
    title: 'Drácula',
    author: 'Bram Stoker',
    genre: 'Terror',
  },
  {
    id: 14,
    image: 'https://placehold.co/300x400?text=Libro+14',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    genre: 'Terror',
  },
  {
    id: 15,
    image: 'https://placehold.co/300x400?text=Libro+15',
    title: 'Veinte poemas de amor y una canción desesperada',
    author: 'Pablo Neruda',
    genre: 'Poesía',
  },
  {
    id: 16,
    image: 'https://placehold.co/300x400?text=Libro+16',
    title: 'Hojas de hierba',
    author: 'Walt Whitman',
    genre: 'Poesía',
  },
  {
    id: 17,
    image: 'https://placehold.co/300x400?text=Libro+17',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    genre: 'Historia',
  },
  {
    id: 18,
    image: 'https://placehold.co/300x400?text=Libro+18',
    title: 'Breve historia del tiempo',
    author: 'Stephen Hawking',
    genre: 'Historia',
  },
]

export default books
